# The file must match particle-linux's DESIRED_CONNECTIVITY_CONF byte for byte.
# If it does not, particled rewrites it and restarts NetworkManager on first boot,
# which is the failure this overlay exists to prevent.
EXPECTED = (
    "# Autogenerated by particle-linux\n"
    "[connectivity]\n"
    "uri=http://connectivity-check.particle.io\n"
    "interval=300\n"
    "enabled=true\n"
)

CONF = '/etc/NetworkManager/conf.d/20-connectivity.conf'


def test_connectivity_conf_exists(host):
    conf = host.file(CONF)
    assert conf.exists
    assert conf.mode == 0o644


def test_connectivity_conf_matches_particle_linux_exactly(host):
    assert host.file(CONF).content_string == EXPECTED
