[org/gnome/shell/extensions/dash-to-dock]
dock-position='BOTTOM'
extend-height=false
dash-max-icon-size=54
show-mounts=false
show-trash=false

[org/gnome/nautilus/preferences]
show-unmounted-drives=false
show-network=false

[org/gnome/desktop/interface]
color-scheme='prefer-dark'
gtk-theme='Yaru-dark'

[org/gnome/desktop/background]
picture-uri='file:///usr/share/backgrounds/Monument_valley_by_orbitelambda.jpg'
picture-uri-dark='file:///usr/share/backgrounds/Monument_valley_by_orbitelambda.jpg'
picture-options='zoom'
