Syntax 4

SectionVerb {
	Value {
		TQ "HiFi"
	}

	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' on,on"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' off,off"
	]
}

SectionDevice."HDMI" {
	Comment "HDMI/DisplayPort output"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},3"
		PlaybackChannels 2
	}
}
