Syntax 4

SectionVerb {
	Value {
		TQ "HiFi"
	}

	EnableSequence [
		cset "name='PRIMARY_MI2S_RX Audio Mixer MultiMedia1' on,on"
		cset "name='Left Mixer Left Playback Switch' on"
		cset "name='Right Mixer Right Playback Switch' on"
		cset "name='PCM Volume' 192,192"
		cset "name='Output 1 Playback Volume' 33,33"
		cset "name='Output 2 Playback Volume' 33,33"
		cset "name='stream0.vol_ctrl0 MultiMedia1 Playback Volu' 65535"
		cset "name='MultiMedia3 Mixer PRIMARY_MI2S_TX' on,on"
		cset "name='Onboard Mic Switch' on"
		cset "name='Left Channel Capture Volume' 8"
		cset "name='Right Channel Capture Volume' 8"
		cset "name='Capture Digital Volume' 192,192"
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' on,on"
	]

	DisableSequence [
		cset "name='PRIMARY_MI2S_RX Audio Mixer MultiMedia1' off,off"
		cset "name='Left Mixer Left Playback Switch' off"
		cset "name='Right Mixer Right Playback Switch' off"
		cset "name='MultiMedia3 Mixer PRIMARY_MI2S_TX' off,off"
		cset "name='Onboard Mic Switch' off"
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' off,off"
	]
}

SectionDevice."Headphones" {
	Comment "ES8388 headphone playback"

	EnableSequence [
		cset "name='PRIMARY_MI2S_RX Audio Mixer MultiMedia1' on,on"
		cset "name='Left Mixer Left Playback Switch' on"
		cset "name='Right Mixer Right Playback Switch' on"
		cset "name='PCM Volume' 192,192"
		cset "name='Output 1 Playback Volume' 33,33"
		cset "name='Output 2 Playback Volume' 33,33"
		cset "name='stream0.vol_ctrl0 MultiMedia1 Playback Volu' 65535"
	]

	DisableSequence [
		cset "name='PRIMARY_MI2S_RX Audio Mixer MultiMedia1' off,off"
		cset "name='Left Mixer Left Playback Switch' off"
		cset "name='Right Mixer Right Playback Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

SectionDevice."HDMI" {
	Comment "HDMI/DisplayPort output"

	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' on,on"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia4' off,off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},3"
		PlaybackChannels 2
	}
}

SectionDevice."Mic" {
	Comment "Onboard microphone capture"

	EnableSequence [
		cset "name='MultiMedia3 Mixer PRIMARY_MI2S_TX' on,on"
		cset "name='Onboard Mic Switch' on"
		cset "name='Left Channel Capture Volume' 8"
		cset "name='Right Channel Capture Volume' 8"
		cset "name='Capture Digital Volume' 192,192"
	]

	DisableSequence [
		cset "name='MultiMedia3 Mixer PRIMARY_MI2S_TX' off,off"
		cset "name='Onboard Mic Switch' off"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},2"
		CaptureChannels 2
	}
}
