[Service]
RestrictAddressFamilies=
RestrictAddressFamilies=AF_NETLINK AF_UNIX AF_QIPCRTR AF_INET AF_INET6

Environment=MM_PLUGIN_DEBUG=qcom-soc
ExecStart=
ExecStart=/usr/sbin/ModemManager --debug

[Unit]
# Ensure rmtfs is up before ModemManager starts
After=rmtfs.service
Requires=rmtfs.service

[Service]
# Add a delay to ensure the modem has initialized and QRTR is populated
ExecStartPre=/bin/sleep 10
